[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pomodoro"
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
rand = "0.8.4"
timer = "0.2.0"
